apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deploy.yaml
  - service.yaml
  - pvc.yaml
  - promtail-configmap.yaml
  - loki-deployment.yaml
  - loki-service.yaml
