apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: owntrack
data:
  loki-config.yaml: |
    limits_config:
      max_query_length: 0
      max_entries_limit_per_query: 1000000
      reject_old_samples: false
      max_query_lookback: 0s
      max_cache_freshness_per_query: 0s
